server:
  port: 8080
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;Database=bookstore
    username: sa
    password: 1234
    platform: mssql
  jpa:
    ddl-auto: update
    hibernate:
    show-sql: true
    database: SQL_SERVER
    database-platform: org.hibernate.dialect.SQLServer2016Dialect
    open-in-view: false
    generate-ddl: true
    hibernate.format_sql: true

